-- naqel-mapserver: Auth / Roles / Permissions / Sessions schema (PostgreSQL)

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

CREATE SCHEMA IF NOT EXISTS public;

-- PERMISSIONS SUPPORT: django_content_type (required by auth_permission)
CREATE TABLE IF NOT EXISTS public.django_content_type (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL,
    CONSTRAINT django_content_type_app_label_model_uniq UNIQUE (app_label, model)
);

-- ROLES: auth_group (group/role container)
CREATE TABLE IF NOT EXISTS public.auth_group (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(150) NOT NULL,
    CONSTRAINT auth_group_name_key UNIQUE (name)
);

-- PERMISSIONS: auth_permission (permission definitions)
CREATE TABLE IF NOT EXISTS public.auth_permission (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL,
    CONSTRAINT auth_permission_content_type_id_codename_uniq UNIQUE (content_type_id, codename),
    CONSTRAINT auth_permission_content_type_id_fkey
        FOREIGN KEY (content_type_id)
        REFERENCES public.django_content_type(id)
        DEFERRABLE INITIALLY DEFERRED
);

-- AUTH: auth_user (user accounts; default Django User)
CREATE TABLE IF NOT EXISTS public.auth_user (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    CONSTRAINT auth_user_username_key UNIQUE (username)
);

-- AUTH↔ROLES: auth_user_groups (users to groups)
CREATE TABLE IF NOT EXISTS public.auth_user_groups (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    group_id integer NOT NULL,
    CONSTRAINT auth_user_groups_user_id_group_id_uniq UNIQUE (user_id, group_id),
    CONSTRAINT auth_user_groups_user_id_fkey
        FOREIGN KEY (user_id)
        REFERENCES public.auth_user(id)
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT auth_user_groups_group_id_fkey
        FOREIGN KEY (group_id)
        REFERENCES public.auth_group(id)
        DEFERRABLE INITIALLY DEFERRED
);

-- ROLES↔PERMISSIONS: auth_group_permissions (groups to permissions)
CREATE TABLE IF NOT EXISTS public.auth_group_permissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_group_permissions_group_id_permission_id_uniq UNIQUE (group_id, permission_id),
    CONSTRAINT auth_group_permissions_group_id_fkey
        FOREIGN KEY (group_id)
        REFERENCES public.auth_group(id)
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT auth_group_permissions_permission_id_fkey
        FOREIGN KEY (permission_id)
        REFERENCES public.auth_permission(id)
        DEFERRABLE INITIALLY DEFERRED
);

-- AUTH↔PERMISSIONS: auth_user_user_permissions (direct user permissions)
CREATE TABLE IF NOT EXISTS public.auth_user_user_permissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_user_user_permissions_user_id_permission_id_uniq UNIQUE (user_id, permission_id),
    CONSTRAINT auth_user_user_permissions_user_id_fkey
        FOREIGN KEY (user_id)
        REFERENCES public.auth_user(id)
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT auth_user_user_permissions_permission_id_fkey
        FOREIGN KEY (permission_id)
        REFERENCES public.auth_permission(id)
        DEFERRABLE INITIALLY DEFERRED
);

-- SESSIONS: django_session (server-side session storage)
CREATE TABLE IF NOT EXISTS public.django_session (
    session_key character varying(40) PRIMARY KEY,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);

CREATE INDEX IF NOT EXISTS django_session_expire_date_idx
    ON public.django_session USING btree (expire_date);

-- PROFILE/APP-AUTH: system_admin_userprofile (project-specific user profile)
CREATE TABLE IF NOT EXISTS public.system_admin_userprofile (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_image character varying(100),
    role character varying(20),
    password_setup_completed boolean NOT NULL DEFAULT false,
    account_creation_date date,
    account_creation_time time without time zone,
    can_access_dashboard boolean NOT NULL DEFAULT false,
    can_access_security boolean NOT NULL DEFAULT false,
    can_access_account_information boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT system_admin_userprofile_user_id_key UNIQUE (user_id),
    CONSTRAINT system_admin_userprofile_user_id_fkey
        FOREIGN KEY (user_id)
        REFERENCES public.auth_user(id)
        DEFERRABLE INITIALLY DEFERRED
);

-- INDEXES: helpful indexes (optional)
CREATE INDEX IF NOT EXISTS auth_user_username_like_idx
    ON public.auth_user USING btree (username varchar_pattern_ops);

CREATE INDEX IF NOT EXISTS auth_permission_content_type_id_idx
    ON public.auth_permission USING btree (content_type_id);

CREATE INDEX IF NOT EXISTS auth_user_groups_user_id_idx
    ON public.auth_user_groups USING btree (user_id);
CREATE INDEX IF NOT EXISTS auth_user_groups_group_id_idx
    ON public.auth_user_groups USING btree (group_id);

CREATE INDEX IF NOT EXISTS auth_group_permissions_group_id_idx
    ON public.auth_group_permissions USING btree (group_id);
CREATE INDEX IF NOT EXISTS auth_group_permissions_permission_id_idx
    ON public.auth_group_permissions USING btree (permission_id);

CREATE INDEX IF NOT EXISTS auth_user_user_permissions_user_id_idx
    ON public.auth_user_user_permissions USING btree (user_id);
CREATE INDEX IF NOT EXISTS auth_user_user_permissions_permission_id_idx
    ON public.auth_user_user_permissions USING btree (permission_id);

