services:
  db:
    image: postgis/postgis:18-3.6
    container_name: naqel_maps_db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./database:/database  # Mount database directory for backups
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: naqel_maps_pgadmin
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  naqel_maps:
    build: .
    container_name: Naqel_Maps
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./database:/database
    command: sh -c "mkdir -p /app/static/css && tailwindcss -i /app/static/src/input.css -o /app/static/css/output.css --minify && until PGPASSWORD=\"$$DB_PASSWORD\" pg_isready -h db -U \"$$DB_USER\" > /dev/null 2>&1; do sleep 1; done && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  pgadmin_data:

