# Generated by Django 6.0.5 on 2026-05-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layer_uploader', '0005_remove_unused_feature_audit_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='status',
            field=models.CharField(choices=[('staged', 'New'), ('nominated', 'Included'), ('rejected_upload', 'Excluded'), ('awaiting_manager', 'Pending')], db_index=True, default='staged', max_length=20),
        ),
        migrations.AlterField(
            model_name='layer',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('completed', 'Completed')], db_index=True, default='draft', max_length=20),
        ),
    ]
