# Generated by Django 6.0.5 on 2026-05-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layer_uploader', '0006_alter_feature_status_alter_layer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='status',
            field=models.CharField(choices=[('staged', 'New'), ('nominated', 'Included'), ('rejected_upload', 'Excluded'), ('awaiting_manager', 'Awaiting review')], db_index=True, default='staged', max_length=20),
        ),
    ]
