# Generated by Django 6.0.5 on 2026-05-21 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layer_uploader', '0008_feature_layer_status_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='feature',
            name='layer_uploader_layer_status_idx',
        ),
    ]
