# Generated by Django 6.0.5 on 2026-06-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layer_uploader', '0009_remove_feature_layer_uploader_layer_status_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='status',
            field=models.CharField(choices=[('staged', 'New'), ('nominated', 'Approved'), ('rejected_upload', 'Rejected'), ('awaiting_manager', 'Awaiting review')], db_index=True, default='staged', max_length=20),
        ),
    ]
