# Generated by Django 6.0.3 on 2026-03-16 20:33

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiyadhRoad',
            fields=[
                ('gid', models.AutoField(db_column='gid', primary_key=True, serialize=False)),
                ('id', models.FloatField(blank=True, db_column='id', null=True)),
                ('objectid', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('osm_id', models.CharField(blank=True, max_length=12, null=True)),
                ('code', models.FloatField(blank=True, null=True)),
                ('fclass', models.CharField(blank=True, max_length=28, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('ref', models.CharField(blank=True, max_length=20, null=True)),
                ('oneway', models.CharField(blank=True, max_length=1, null=True)),
                ('maxspeed', models.FloatField(blank=True, null=True)),
                ('layer', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bridge', models.CharField(blank=True, max_length=1, null=True)),
                ('tunnel', models.CharField(blank=True, max_length=1, null=True)),
                ('shape_length', models.DecimalField(blank=True, db_column='shape_leng', decimal_places=6, max_digits=20, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=3857)),
                ('road_closure', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'riyadh_roads',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LineEditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('edit_type', models.CharField(default='LINE EDIT', max_length=50)),
                ('geometry', models.JSONField(help_text='LineString geometry in GeoJSON format')),
                ('feature_type', models.CharField(blank=True, max_length=200, null=True)),
                ('current_feature_label', models.CharField(blank=True, max_length=200, null=True)),
                ('fields_data', models.JSONField(blank=True, default=dict, help_text='Fields section data')),
                ('tags_data', models.JSONField(blank=True, default=list, help_text='Tags section data')),
                ('relations_data', models.JSONField(blank=True, default=list, help_text='Relations section data')),
                ('road_closure', models.IntegerField(default=0, help_text='Road closure flag: 0 = open, 1 = closed')),
                ('is_riyadh_road', models.BooleanField(default=False, help_text='True when this edit request targets a RiyadhRoad feature')),
                ('riyadh_road_id', models.IntegerField(blank=True, help_text='Primary key of the RiyadhRoad feature when applicable', null=True)),
                ('parent_approved_line_id', models.IntegerField(blank=True, help_text='ID of the approved line being edited', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_edit_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_line_edits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Line Edit Request',
                'verbose_name_plural': 'Line Edit Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
