# Generated by Django 6.0 on 2025-12-28 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LineEditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('edit_type', models.CharField(default='LINE EDIT', max_length=50)),
                ('geometry', models.JSONField(help_text='LineString geometry in GeoJSON format')),
                ('feature_type', models.CharField(blank=True, max_length=200, null=True)),
                ('current_feature_label', models.CharField(blank=True, max_length=200, null=True)),
                ('fields_data', models.JSONField(blank=True, default=dict, help_text='Fields section data')),
                ('tags_data', models.JSONField(blank=True, default=list, help_text='Tags section data')),
                ('relations_data', models.JSONField(blank=True, default=list, help_text='Relations section data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_edit_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_line_edits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Line Edit Request',
                'verbose_name_plural': 'Line Edit Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
