# Generated by Django 6.0 on 2025-12-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineeditrequest',
            name='parent_approved_line_id',
            field=models.IntegerField(blank=True, help_text='ID of the approved line being edited', null=True),
        ),
    ]
