# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapping", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lineeditrequest",
            name="geometry_changed",
            field=models.BooleanField(
                default=False,
                help_text="True when proposed geometry differs from original_geometry",
            ),
        ),
        migrations.AddField(
            model_name="lineeditrequest",
            name="original_geometry",
            field=models.JSONField(
                blank=True,
                help_text="Pre-edit geometry from base network (GeoJSON, WGS84)",
                null=True,
            ),
        ),
    ]
