# Generated by Django 6.0.3 on 2026-03-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0002_lineeditrequest_original_geometry_and_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineeditrequest',
            name='has_geometry_change',
            field=models.BooleanField(db_column='has_geometry_change', default=False, help_text='Legacy alias for geometry_changed (DB: has_geometry_change).'),
        ),
    ]
