# Generated by Django 6.0.2 on 2026-03-04 14:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0002_lineeditrequest_parent_approved_line_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiyadhRoad',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(help_text='Road geometry in WGS84', srid=4326)),
                ('objectid', models.BigIntegerField(blank=True, null=True)),
                ('osm_id', models.CharField(blank=True, help_text='OpenStreetMap ID', max_length=12, null=True)),
                ('code', models.IntegerField(blank=True, help_text='Road classification code', null=True)),
                ('fclass', models.CharField(blank=True, help_text='Road feature class (e.g., motorway, primary, secondary)', max_length=28, null=True)),
                ('name', models.CharField(blank=True, help_text='Road name', max_length=100, null=True)),
                ('ref', models.CharField(blank=True, help_text='Road reference number', max_length=20, null=True)),
                ('oneway', models.CharField(blank=True, help_text='One-way indicator (Y/N)', max_length=1, null=True)),
                ('maxspeed', models.IntegerField(blank=True, help_text='Maximum speed limit', null=True)),
                ('layer', models.FloatField(blank=True, help_text='Layer/level (for bridges/tunnels)', null=True)),
                ('bridge', models.CharField(blank=True, help_text='Bridge indicator (Y/N)', max_length=1, null=True)),
                ('tunnel', models.CharField(blank=True, help_text='Tunnel indicator (Y/N)', max_length=1, null=True)),
                ('shape_length', models.FloatField(blank=True, help_text='Length of the road segment', null=True)),
                ('road_closure', models.IntegerField(db_column='road_closure', default=0, help_text='Road closure flag: 0 = open, 1 = closed')),
            ],
            options={
                'verbose_name': 'Riyadh Road',
                'verbose_name_plural': 'Riyadh Roads',
                'db_table': 'riyadh_roads',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='lineeditrequest',
            name='is_riyadh_road',
            field=models.BooleanField(default=False, help_text='True when this edit request targets a RiyadhRoad feature'),
        ),
        migrations.AddField(
            model_name='lineeditrequest',
            name='riyadh_road_id',
            field=models.IntegerField(blank=True, help_text='Primary key of the RiyadhRoad feature when applicable', null=True),
        ),
        migrations.AddField(
            model_name='lineeditrequest',
            name='road_closure',
            field=models.IntegerField(default=0, help_text='Road closure flag: 0 = open, 1 = closed'),
        ),
    ]
