# Generated by Django 6.0.5 on 2026-05-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0006_lineeditrequest_request_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineeditrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Road edit request', 'verbose_name_plural': 'Road edit requests'},
        ),
        migrations.AlterField(
            model_name='lineeditrequest',
            name='current_feature_label',
            field=models.CharField(blank=True, help_text='Display feature type for this road (e.g. Motorway).', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lineeditrequest',
            name='edit_type',
            field=models.CharField(blank=True, default='', help_text='Legacy workflow marker: DELETE or Layer Upload only; use request_category in UI.', max_length=50),
        ),
        migrations.AlterField(
            model_name='lineeditrequest',
            name='feature_type',
            field=models.CharField(blank=True, help_text='Deprecated mirror of current_feature_label; kept for compatibility.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lineeditrequest',
            name='geometry',
            field=models.JSONField(help_text='Road geometry as GeoJSON LineString or MultiLineString'),
        ),
        migrations.AlterField(
            model_name='lineeditrequest',
            name='layer_upload_feature_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='layer_uploader.Feature pk for layer_upload requests', null=True),
        ),
        migrations.AlterField(
            model_name='lineeditrequest',
            name='request_category',
            field=models.CharField(blank=True, default='', help_text='Approval queue category key (see mapping.approval_categories).', max_length=32),
        ),
    ]
