# Generated by Django 6.0.3 on 2026-03-16 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('role', models.CharField(blank=True, choices=[('manager', 'Manager'), ('editor', 'Editor')], max_length=20, null=True)),
                ('password_setup_completed', models.BooleanField(default=False)),
                ('account_creation_date', models.DateField(blank=True, null=True)),
                ('account_creation_time', models.TimeField(blank=True, null=True)),
                ('can_access_dashboard', models.BooleanField(default=False)),
                ('can_access_security', models.BooleanField(default=False)),
                ('can_access_account_information', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
