# Generated by Django 6.0 on 2025-12-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('manager', 'Manager'), ('editor', 'Editor')], max_length=20, null=True),
        ),
    ]
