# Generated by Django 6.0.5 on 2026-05-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_access_layer_uploader',
            field=models.BooleanField(default=False),
        ),
    ]
