# Generated by Django 6.0 on 2025-12-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_admin', '0002_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_setup_completed',
            field=models.BooleanField(default=False),
        ),
    ]
