# Generated by Django 6.0 on 2025-12-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_admin', '0003_userprofile_password_setup_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_creation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='account_creation_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
