# Generated by Django 6.0 on 2025-12-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_admin', '0004_userprofile_account_creation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_access_account_information',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_access_dashboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_access_security',
            field=models.BooleanField(default=False),
        ),
    ]
