# Generated by Django 6.0.3 on 2026-03-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SymbologyStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Human-readable feature label, e.g. 'Motorway' or 'Pipeline'.", max_length=128, unique=True)),
                ('line_color', models.CharField(help_text='Stroke color for the line (hex, e.g. #2563eb).', max_length=16)),
                ('glow_color', models.CharField(help_text='Outer glow color around the line (hex).', max_length=16)),
                ('line_width', models.FloatField(help_text='Base line width; may be overridden globally in the catalog.')),
                ('glow_width', models.FloatField(help_text='Width of the outer glow around the line.')),
                ('glow_opacity', models.FloatField(help_text='Opacity of the glow (0.0 - 1.0).')),
                ('marker_color', models.CharField(help_text='Fill color for vertex markers (hex).', max_length=16)),
                ('marker_glow_color', models.CharField(help_text='Glow color for vertex markers (hex).', max_length=16)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive styles are ignored when building the symbology catalog.')),
            ],
            options={
                'verbose_name': 'Symbology Style',
                'verbose_name_plural': 'Symbology Styles',
                'ordering': ['label'],
            },
        ),
    ]
