# Generated by Django 6.0.4 on 2026-04-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbology', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbologystyle',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Legacy column; the catalog is built only from symbology.json, not this table.'),
        ),
    ]
